print("hello M.6/14")
print("Watcharaporn Laochai")
print("Nice")
print("17 years old")
print("Chonradsadornumrung")
print("love cat")
print("30 August 2004")
print("Live in Chonburi")
print("Anime lovers")
print("Video created")
#น.ส.วัชรภรณ์ เหลาชัย ม.6/14 43